__include__: [
  '../rtdetrv2_dinov3_vit_6x_coco2017_5k.yml',
]

# Main setting in your experiments.
output_dir: /data2/ZJ_output2/Ablation/layers_7_15_23

DINOv3Encoder:
  feature_layers: [7, 15, 23]
  pyramid_style: layerwise_fused
