__include__: [
  '../rtdetrv2_dinov3_vit_6x_coco2017_5k.yml',
]

# Single deep layer ablation.
output_dir: /data2/ZJ_output2/Ablation/layers_23

DINOv3Encoder:
  feature_layers: [23]
  pyramid_style: avg
