__include__: [
  '../rtdetrv2_dinov3_vit_6x_coco2017_5k.yml',
]

# Three-layer late-biased ablation.
output_dir: /data2/ZJ_output2/Ablation/layers_11_17_23
# 开启 AMP
use_amp: True

scaler:
  type: GradScaler
  enabled: True
DINOv3Encoder:
  feature_layers: [11, 17, 23]
  pyramid_style: avg
