__include__: [
  './rtdetrv2_dinov3_vit_6x_coco.yml',
]

# ETF finetune config on top of a converged non-ETF checkpoint.
# Launch training with: -r path/to/non_etf_best.pth
# output_dir: /data2/ZJ_output2/Ablation/ETF
output_dir: /data2/ZJ_output2/Ablation/ETF_amc_0.1_small
checkpoint_freq: 0
eval_freq: 5
save_last_freq: 1

RTDETR:
  backbone: IdentityBackbone
  encoder: DINOv3Encoder
  decoder: RTDETRTransformerv2

criterion: RTDETRCriterionv2
postprocessor: RTDETRPostProcessor

IdentityBackbone: {}

DINOv3Encoder:
  model_name_or_path: ckpts/dinov3_vits16.pth
  feature_layers: [3, 7, 11]
  freeze_backbone: True
  pyramid_style: layerwise_fused

RTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_layers: 6
  etf_confusion_classes: [0, 60, 56, 2, 73, 39, 41, 58, 13, 45, 57, 7, 6, 9, 62, 26, 8, 24, 51, 25, 3, 40, 69, 5, 72, 43, 32, 65, 1, 59, 33, 14, 71, 50]
  # etf_confusion_classes: [24, 26, 44, 42, 41, 43, 0, 56, 7, 70, 39, 2, 45, 40, 31, 75, 47, 13, 49, 28, 78]
  etf_scale_init: 10.0
  etf_scale_trainable: true
  etf_seed: 0
  query_select_method: default


RTDETRCriterionv2:
  weight_dict: {loss_vfl: 1, loss_amc: 0.05, loss_bbox: 5, loss_giou: 2}
  losses: ['vfl', 'boxes', 'amc']
  amc_distance: cosine



# # Early stop disabled when patience <= 0.
# early_stop_patience: 0
# early_stop_metric: coco_eval_bbox
# early_stop_index: 0
# early_stop_mode: max
# early_stop_min_delta: 0.001

