__include__: [
  './rtdetrv2_dinov3_vit_6x_coco.yml',
  '../dataset/coco2017_1k_detection.yml',
]

output_dir: /data2/ZJ_output2/output21_oco2017_1k_vitl16_SingleETF

epoches: 50
checkpoint_freq: 0
eval_freq: 1
save_last_freq: 1

eval_spatial_size: [640, 640]

train_dataloader:
  batch_size: 32
  num_workers: 32
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 35
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  collate_fn:
    scales: [576, 608, 640, 640, 672, 704]
    stop_epoch: 35

lr_scheduler:
  type: MultiStepLR
  milestones: [35, 45]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 200

val_dataloader:
  batch_size: 32
  num_workers: 16

RTDETRCriterionv2:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2}
  losses: ['vfl', 'boxes']

RTDETRTransformerv2:
  num_levels: 3
  num_layers: 4
  num_points: [4, 4, 4]
  cls_head_type: linear
  # cls_head_share: true
  # freeze_bbox_head: true
  query_select_method: default
  etf_confusion_classes: [2, 5, 7, 0, 9, 73, 56, 8]
  etf_scale_init: 10.0
  etf_scale_trainable: true
  etf_seed: 0
