__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

use_amp: True
output_dir: /data2/ZJ_output2/output22_oco2017_1k_vitl16_best



